<?php

namespace Openify\Bundle\CustomerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public function findAllCustomersForGrid()
    {
        return $this->createQueryBuilder ('c')
            ->select ('c')
            ;
    }
}
